server:
  port: 8060

spring:
  redis:
    host: 
    port: 
    password: 
  datasource:
    druid:
      username: 
      password: 
      url: 
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.fm.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*Mapper.xml


### JWT
jwt-secret: 
